### ISSUE TITLE
Проблем със стартирането на тестовете.

### ISSUE THREAD

**Issue by dddobrev** [luchob/softuni-music-db#38]
Лъчо Здравей,
Тестовете при мен не успяха да стартират.   Минава само този:

`@SpringBootTest
class AutoWorkShopApplicationTests {

    @Test
    void contextLoads() {
    }

}`

Драмите започват още от тук:
`  private AutoWorkShopUserService serviceToTest;

    @Mock
    UserRepository mockUserRepository;

    @BeforeEach
    public void setUp() {
        serviceToTest = new AutoWorkShopUserService(mockUserRepository);
    }

    @Test
    void testUserNotFound() {
        Assertions.assertThrows(
                UsernameNotFoundException.class, () -> {
                    serviceToTest.loadUserByUsername("user_not_found");
                }
        );
    }`
интересно, че след старта на тестовете  иска да ги направя  **publuc**. Това е грешката

`org.junit.runners.model.InvalidTestClassError: Invalid test class 'com.example.AutoWorkShop.service.impl.AutoWorkShopUserServiceTest':
  1. Method testExistingUser() should be public
  2. Method testUserNotFound() should be public

	at org.junit.runners.ParentRunner.validate(ParentRunner.java:525)
	at org.junit.runners.ParentRunner.<init>(ParentRunner.java:102)
	at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:84)
	at org.junit.runners.JUnit4.<init>(JUnit4.java:23)
	at org.junit.internal.builders.JUnit4Builder.runnerForClass(JUnit4Builder.java:10)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:37)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at org.junit.internal.requests.ClassRequest.createRunner(ClassRequest.java:28)
	at org.junit.internal.requests.MemoizingRequest.getRunner(MemoizingRequest.java:19)
	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:36)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:50)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)`

Като ги направя публични излиза: 
`org.opentest4j.AssertionFailedError: Unexpected exception type thrown ==> expected: <org.springframework.security.core.userdetails.UsernameNotFoundException> but was: <java.lang.NullPointerException>

	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:65)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:37)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:2952)
	at com.example.AutoWorkShop.service.impl.AutoWorkShopUserServiceTest.testUserNotFound(AutoWorkShopUserServiceTest.java:38)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: java.lang.NullPointerException: Cannot invoke "com.example.AutoWorkShop.service.impl.AutoWorkShopUserService.loadUserByUsername(String)" because "this.serviceToTest" is null
	at com.example.AutoWorkShop.service.impl.AutoWorkShopUserServiceTest.lambda$testUserNotFound$0(AutoWorkShopUserServiceTest.java:40)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:55)
	... 28 more
`
"java.lang.NullPointerException: Cannot invoke "com.example.AutoWorkShop.repository.UserRepository.findAll()" because "this.mockedUserRepository" is null" - това при теста в class UserServiceImplTest 
Счупих си главата и не можах да ги подкарам. Започнал съм на jdk 15, ако това има значение.
Моля за някакви идеи, ако е удобно. 
Много Благодаря!

Поздрави,
Митко

**Comment by luchob** [comment]
Ей, Митко, хванали са те за гушата тези тестове. :-)

Забележи част от stack trace-a:

```
BlockJUnit4ClassRunner
```

JUnit4 виждам аз :P Дай вместо да анотираме тестовете с `org.junit.Test` да пробваме с `org.junit.jupiter.api.Test`, което си намерисва на JUnit5. Тогава - войля:

<img width="481" alt="Screenshot 2021-04-04 at 8 24 07" src="https://user-images.githubusercontent.com/10339738/113499509-27409200-951f-11eb-9dbe-079a7ab5c983.png">

Даже както пише в документацията - може да не са ти public методите ;-)

Поздрави,
Л.

**Comment by dddobrev** [comment]
Eeeee Голям си Лъчо. Да си жив и здрав! Явно умората си казва думата :)
Благодаря за пореден път!
Продължавам с другите тестове.
